export const MODEL_SEED_DATA = [
  {
    name: 'GPT-4o',
    lab: 'OpenAI',
    description:
      'Most capable OpenAI model. Excels at complex reasoning, coding, and multimodal tasks with text and images. Best choice for production applications requiring top-tier intelligence.',
    tags: ['text', 'vision', 'code', 'reasoning', 'multimodal'],
    contextWindow: 128000,
    inputPrice: 0.005,
    outputPrice: 0.015,
    rating: 4.8,
    reviews: 2341,
    isNew: false,
    isFeatured: true,
    category: 'multimodal',
    imageUrl: null,
    useCases: ['coding', 'analysis', 'writing', 'vision'],
    speed: 'medium',
    bestFor: 'complex tasks requiring reasoning and vision',
  },
  {
    name: 'Claude Opus 4.6',
    lab: 'Anthropic',
    description:
      'Anthropic\'s most intelligent model. Exceptional at nuanced understanding, long-context analysis, and following complex instructions with near-human accuracy.',
    tags: ['text', 'code', 'analysis', 'reasoning', 'long-context'],
    contextWindow: 200000,
    inputPrice: 0.015,
    outputPrice: 0.075,
    rating: 4.9,
    reviews: 1876,
    isNew: false,
    isFeatured: true,
    category: 'language',
    imageUrl: null,
    useCases: ['analysis', 'writing', 'coding', 'research'],
    speed: 'slow',
    bestFor: 'complex analysis and long-form tasks',
  },
  {
    name: 'Claude Sonnet 4.6',
    lab: 'Anthropic',
    description:
      'The optimal balance between intelligence and speed. Great for high-volume tasks, customer support, and coding assistance at a lower cost than Opus.',
    tags: ['text', 'code', 'fast', 'balanced', 'customer-support'],
    contextWindow: 200000,
    inputPrice: 0.003,
    outputPrice: 0.015,
    rating: 4.7,
    reviews: 3102,
    isNew: false,
    isFeatured: true,
    category: 'language',
    imageUrl: null,
    useCases: ['coding', 'customer-support', 'writing', 'analysis'],
    speed: 'fast',
    bestFor: 'balanced performance for everyday tasks',
  },
  {
    name: 'Gemini 2.5 Pro',
    lab: 'Google',
    description:
      'Google\'s most advanced model with breakthrough thinking capabilities. Excels at STEM, coding, and tasks requiring deep analytical reasoning.',
    tags: ['text', 'vision', 'code', 'reasoning', 'STEM'],
    contextWindow: 1000000,
    inputPrice: 0.00125,
    outputPrice: 0.01,
    rating: 4.7,
    reviews: 1543,
    isNew: true,
    isFeatured: true,
    category: 'multimodal',
    imageUrl: null,
    useCases: ['coding', 'analysis', 'research', 'STEM'],
    speed: 'medium',
    bestFor: 'STEM tasks and long document analysis',
  },
  {
    name: 'Gemini 2.0 Flash',
    lab: 'Google',
    description:
      'Blazing fast multimodal model optimized for real-time applications. Best speed-to-quality ratio for high-throughput workloads.',
    tags: ['text', 'vision', 'fast', 'real-time', 'efficient'],
    contextWindow: 1000000,
    inputPrice: 0.0001,
    outputPrice: 0.0004,
    rating: 4.5,
    reviews: 987,
    isNew: true,
    isFeatured: false,
    category: 'multimodal',
    imageUrl: null,
    useCases: ['real-time', 'chatbots', 'classification'],
    speed: 'very-fast',
    bestFor: 'high-speed, cost-efficient applications',
  },
  {
    name: 'GPT-4o mini',
    lab: 'OpenAI',
    description:
      'Smaller, faster, and more affordable version of GPT-4o. Perfect for simple tasks, chatbots, and classification where cost is a priority.',
    tags: ['text', 'fast', 'affordable', 'classification', 'chatbot'],
    contextWindow: 128000,
    inputPrice: 0.00015,
    outputPrice: 0.0006,
    rating: 4.4,
    reviews: 4215,
    isNew: false,
    isFeatured: false,
    category: 'language',
    imageUrl: null,
    useCases: ['chatbots', 'classification', 'summarization'],
    speed: 'very-fast',
    bestFor: 'cost-efficient everyday tasks',
  },
  {
    name: 'Llama 3.3 70B',
    lab: 'Meta',
    description:
      'Meta\'s powerful open-source model. Competitive with closed-source models at a fraction of the cost. Self-hostable for full data privacy.',
    tags: ['text', 'code', 'open-source', 'self-hosted', 'affordable'],
    contextWindow: 128000,
    inputPrice: 0.00059,
    outputPrice: 0.00079,
    rating: 4.5,
    reviews: 2108,
    isNew: false,
    isFeatured: false,
    category: 'language',
    imageUrl: null,
    useCases: ['coding', 'writing', 'self-hosted'],
    speed: 'fast',
    bestFor: 'open-source deployments with data privacy needs',
  },
  {
    name: 'Mistral Large',
    lab: 'Mistral AI',
    description:
      'Mistral\'s flagship model with top-tier reasoning for complex tasks. Strong multilingual capabilities and excellent code generation.',
    tags: ['text', 'code', 'multilingual', 'reasoning', 'European'],
    contextWindow: 128000,
    inputPrice: 0.002,
    outputPrice: 0.006,
    rating: 4.5,
    reviews: 876,
    isNew: false,
    isFeatured: false,
    category: 'language',
    imageUrl: null,
    useCases: ['coding', 'multilingual', 'analysis'],
    speed: 'medium',
    bestFor: 'multilingual tasks and European data compliance',
  },
  {
    name: 'DeepSeek R1',
    lab: 'DeepSeek',
    description:
      'Reasoning-focused model that shows its thinking process step-by-step. Exceptional for math, science, and logic problems at a very low cost.',
    tags: ['reasoning', 'math', 'science', 'chain-of-thought', 'affordable'],
    contextWindow: 64000,
    inputPrice: 0.00055,
    outputPrice: 0.00219,
    rating: 4.6,
    reviews: 1234,
    isNew: true,
    isFeatured: false,
    category: 'language',
    imageUrl: null,
    useCases: ['math', 'science', 'logic', 'research'],
    speed: 'medium',
    bestFor: 'complex reasoning and mathematical problems',
  },
  {
    name: 'Whisper Large v3',
    lab: 'OpenAI',
    description:
      'State-of-the-art speech recognition model. Supports 99 languages with exceptional accuracy. Perfect for transcription and voice interfaces.',
    tags: ['audio', 'speech-to-text', 'multilingual', 'transcription'],
    contextWindow: 0,
    inputPrice: 0.006,
    outputPrice: 0,
    rating: 4.7,
    reviews: 3421,
    isNew: false,
    isFeatured: false,
    category: 'audio',
    imageUrl: null,
    useCases: ['transcription', 'voice-interface', 'subtitles'],
    speed: 'fast',
    bestFor: 'audio transcription and voice recognition',
  },
  {
    name: 'DALL·E 3',
    lab: 'OpenAI',
    description:
      'Advanced image generation model with precise prompt following. Creates high-quality, detailed images from text descriptions. Integrated with GPT-4 for superior accuracy.',
    tags: ['image-generation', 'creative', 'design', 'art'],
    contextWindow: 0,
    inputPrice: 0.04,
    outputPrice: 0,
    rating: 4.6,
    reviews: 2876,
    isNew: false,
    isFeatured: false,
    category: 'vision',
    imageUrl: null,
    useCases: ['design', 'marketing', 'creative-content'],
    speed: 'medium',
    bestFor: 'image generation and creative design',
  },
  {
    name: 'Claude Haiku 4.5',
    lab: 'Anthropic',
    description:
      'The fastest Claude model. Near-instant responses for high-throughput applications. Ideal for real-time features like autocomplete, tagging, and live chat.',
    tags: ['fast', 'affordable', 'real-time', 'efficient', 'lightweight'],
    contextWindow: 200000,
    inputPrice: 0.00025,
    outputPrice: 0.00125,
    rating: 4.4,
    reviews: 2654,
    isNew: true,
    isFeatured: false,
    category: 'language',
    imageUrl: null,
    useCases: ['real-time', 'autocomplete', 'classification', 'tagging'],
    speed: 'very-fast',
    bestFor: 'real-time features needing near-instant responses',
  },
];
